some feature and fixes for telegram bot
Gozargah/Marzban pull request #1233
Opened 2024-08-08 10:30 UTC by T3ST3ST3R0N

2024-08-08 10:40 UTC, erfjab approved these changes
Great, it's nice to see you again.

2024-08-08 10:48 UTC, erfjab requested changes
Please change your branch to dev.
Telegram Refactor's branch is for aiogram..

2024-08-30 14:06 UTC, erfjab commented
Update your pr so we can merge it before the new Release.

2024-08-30 22:43 UTC, M03ED approved these changes

2024-08-30 23:28 UTC, closed without merging