Next user planning
Gozargah/Marzban pull request #1420
Opened 2024-11-06 21:33 UTC by MuhammadAshouri

These changes enable planning the next data_limit and expire_date for each user with 'limited' or 'expired' statuses

2024-11-07 06:48 UTC, M03ED requested changes

2024-11-07 06:48 UTC, M03ED commented on app/jobs/review_users.py
> +            if (limited or expired):
better to use 
```python
if (limited or expired) and user.next_user is not None:
```

2024-11-07 06:48 UTC, M03ED commented on app/telegram/handlers/report.py
> +
add more detail about user, expire and data limit, add_remaining_traffic
also add details about next user to create user and modify user report

2024-11-07 06:48 UTC, M03ED commented on app/utils/report.py
> +            discord.report_user_data_reset_by_next(
i can't find this function in discord module

2024-11-07 16:38 UTC, ImMohammad20000 commented
بنظرم خوبه مرج کنیم

2024-11-08 11:47 UTC, M03ED approved these changes

2024-11-08 12:07 UTC, merged