Webhook notifications support (WIP)
Gozargah/Marzban pull request #159
Opened 2023-04-03 11:26 UTC by govfvck

fixes #72

Implements webhook notifications!
Events on a user will be sent to a webhook address provided by the `WEBHOOK_ADDRESS` config variable.

also updated readme for more info

this pull request is a work in progress and needs some review. things might change!

2023-04-03 13:45 UTC, SaintShit requested changes
Please add a event handler that runs send_notifications on shutdown event before shutdown.

2023-04-03 13:45 UTC, SaintShit commented on app/jobs/send_notifications.py
> +
Please add a event handler that runs send_notifications on shutdown event before shutdown.

2023-04-03 19:36 UTC, merged

2023-04-03 19:36 UTC, SaintShit commented
thanks.

2023-04-22 23:20 UTC, AC-Lover commented
I tested it, unfortunately it didn't work at all =(
Please check and fix, thank you

2023-04-23 22:58 UTC, AC-Lover commented
Hello
Why does it not work at all on `https`?
Must be `http` to work
Please check, I think it has a bug