Ru language
Gozargah/Marzban pull request #472
Opened 2023-08-16 15:45 UTC by Iambabyninja

Add Russian language in web panel

2023-08-17 21:26 UTC, celgus approved these changes

2023-08-21 17:33 UTC, fL1pSt3r approved these changes
Everything is translated well. But I would translate userDialog.expiryDate as "Дата окончания", but that's a small thing.

2023-08-22 01:54 UTC, kaixRaf approved these changes

2023-08-23 09:13 UTC, SaintShit commented
I've merged this to `dev` branch currently

2023-09-03 21:21 UTC, master88wi commented
Add Russian language in web panel

2023-09-12 13:33 UTC, aurora1369 approved these changes

2023-09-14 11:38 UTC, SokolovOne commented
Good!

2023-09-14 11:44 UTC, SokolovOne reviewed
Спасибо огромное!

2023-09-14 11:46 UTC, SokolovOne commented on app/dashboard/public/locales/ru.json
> +"resetAllUsage.success": "расход трафика успешно сброшен.",
"Р"асход

2023-09-14 11:46 UTC, SokolovOne reviewed
Очепятка

2023-09-14 17:06 UTC, SokolovOne approved these changes

2023-09-14 17:07 UTC, SokolovOne approved these changes

2023-10-10 21:09 UTC, marat2509 requested changes
`"resetAllUsage.success": "расход трафика успешно сброшен.",`
Вместо "расход" должно быть "Расход":
`"resetAllUsage.success": "Расход трафика успешно сброшен.",`

2023-10-30 06:47 UTC, sblvkr approved these changes

2023-11-18 10:50 UTC, merged