Increase username limit to 64 characters
Gozargah/Marzban pull request #625
Opened 2023-11-08 04:32 UTC by lilcheti

2023-11-08 11:17 UTC, M03ED requested changes
database changes need migration file to sync database with code and you need to make and upload it with code 
also you did this change on master branch , changes and new features first come on dev branch then come to master branch

2023-11-08 11:17 UTC, M03ED commented on app/db/models.py
it must be 64 not 66

2023-11-08 18:29 UTC, kastov commented
Does xray supports that lenth?

2023-11-09 06:28 UTC, lilcheti commented on app/db/models.py
It was 34 how is that?

2023-11-09 06:42 UTC, kastov commented
> > Does Xray-core supports that lenght?
> 
> A valid mail's username length is 64 characters 64 (Username) + 1 (@) + 255 (Domain Name) = 320 [i.e. example@localhost ]
> 
> How can Xray-core not accept that?

Not sure about 320 in total. Many sources say that the maximum length is around 254-256 characters.

2023-11-11 08:00 UTC, SaintShit commented
this isn't enough, you need to provide a migration script too

2023-12-28 10:58 UTC, closed without merging