dynamic subscription path
Gozargah/Marzban pull request #633
Opened 2023-11-16 06:46 UTC by ImMohammad20000

2023-11-16 14:39 UTC, M03ED commented on config.py
> +if not XRAY_SUBSCRIPTION_PATH.startswith("/"):
no need to add / in start , just add them in api

2023-11-16 14:39 UTC, M03ED commented on config.py
> +XRAY_SUBSCRIPTION_PATH = config("XRAY_SUBSCRIPTION_PATH", default="/sub/")
receive XRAY_SUBSCRIPTION_PATH like this 
XRAY_SUBSCRIPTION_PATH = config("XRAY_SUBSCRIPTION_PATH", default="sub")

2023-11-16 14:40 UTC, M03ED requested changes
this can be better

2023-11-16 14:40 UTC, M03ED commented on app/models/user.py
> +            return f"{XRAY_SUBSCRIPTION_URL_PREFIX}{XRAY_SUBSCRIPTION_PATH}{token}"
return f"{XRAY_SUBSCRIPTION_URL_PREFIX}/{XRAY_SUBSCRIPTION_PATH}/{token}"

2023-11-21 10:46 UTC, ImMohammad20000 commented
فکر نمیکنم /api مشکلی درست کنه🤔 باشه چک میکنم

2023-12-28 11:00 UTC, SaintShit commented
there lots of file changes here, I can't check the real changes, I appreciate it if you make another PR for this

2023-12-28 11:00 UTC, closed without merging

2023-12-28 11:10 UTC, ImMohammad20000 commented
Ok