feat(cli): added admin usage to table of admins
Gozargah/Marzban pull request #795
Opened 2024-02-15 02:53 UTC by danielsoheil

2024-02-15 02:55 UTC, danielsoheil commented
![image](https://github.com/Gozargah/Marzban/assets/89687335/1e2f45e5-d316-4d8e-8929-81c3145ef837)

2024-02-20 19:53 UTC, danielsoheil commented
With this database structure it's a little bit complicated, I think it's not worth it.

2024-02-20 20:01 UTC, M03ED commented on cli/admin.py
> +        return db.execute(text(f'select sum(used_traffic) / 1024 / 1024 / 1024 from (select * from node_user_usages join (select * from users where admin_id = {admin_id}) as users on users.id = node_
also you can disable node_user_usages with env

2024-02-21 01:08 UTC, danielsoheil commented on cli/admin.py
> +        return db.execute(text(f'select sum(used_traffic) / 1024 / 1024 / 1024 from (select * from node_user_usages join (select * from users where admin_id = {admin_id}) as users on users.id = node_
> why you use node_user_usages table for calculating ? we already have used_traffic column in users table

why we have same data in two different location? which one is SSOT?

2024-02-21 01:13 UTC, danielsoheil commented on cli/admin.py
> +        return db.execute(text(f'select sum(used_traffic) / 1024 / 1024 / 1024 from (select * from node_user_usages join (select * from users where admin_id = {admin_id}) as users on users.id = node_
> also you can disable node_user_usages with env

I can not understand, can you explain more?

2024-02-21 05:38 UTC, danielsoheil commented
> Hi, that's great, could you please use sqlalchemy's API rather than executing raw query?

done.

2024-02-21 05:40 UTC, danielsoheil commented on cli/admin.py
> +        return db.execute(text(f'select sum(used_traffic) / 1024 / 1024 / 1024 from (select * from node_user_usages join (select * from users where admin_id = {admin_id}) as users on users.id = node_
> > > why you use node_user_usages table for calculating ? we already have used_traffic column in users table
> > 
> > 
> > why we have same data in two different location? which one is SSOT?
> 
> node_user_usages it's same as used_traffic but it's separated for each node Also if you remove a node that's gonna be deleted too But used_traffic will be changed if you reset usage

Okey
I used used_traffic in users table.

2024-02-21 13:50 UTC, M03ED requested changes

2024-02-21 13:50 UTC, M03ED commented on app/db/models.py
why we have duplicate function ? there both do same thing also we have lifetime_used_traffic function and you can calculate reseted_usage way faster
`reseted_usage = lifetime_used_traffic - used_traffic`

2024-02-21 13:50 UTC, M03ED commented on cli/admin.py
use power instead of Multiplication
`usage // (1024 ** 3)`

2024-02-21 13:53 UTC, M03ED commented on cli/admin.py
actually its better to use `from app.utils.system import readable_size` function

2024-02-22 02:49 UTC, danielsoheil commented on app/db/models.py
that's not same, you have a better idea?

lifetime_used_traffic is not faster :/
lifetime_used_traffic will get all data from database and calculate it in python
by reseted_usage that I add, you will get calculated data from database

2024-02-22 07:40 UTC, M03ED commented on app/db/models.py
we are doing same thing twice, you can do less job
Another way to avoid more jobs is that we calculate rested usage then for  lifetime_used_traffic sum rested usage with used traffic to calculate lifetime_used_traffic

2024-02-22 08:34 UTC, danielsoheil commented on app/db/models.py
you can do it yourself.

2024-02-24 02:22 UTC, danielsoheil commented
I implemented this feature for my self but one of my friends need this. i told her this is going add in official version, when do you think you can work on it?

2024-02-27 12:57 UTC, danielsoheil commented
guys, i need this
implement it your self or merge this

2024-03-14 20:59 UTC, tohid3aeed commented on app/db/models.py
من در مورد نحوه محاسبه ریست یوزیج ابن کار رو به صورت دستی انجام میدم
مصرف کل به علاوه مانده حجم که مقدار کامل رو درمیارم
برای مثال 
اکانت ۵۰ گیگ دوبار کامل مصرف شده ریست شده و حجم کل ۱۳۰ گیگ هستش
۱۳۰ گیگ به اضافه ۲۰ گیگ مانده از ۵۰ گیگ 
عکسی که پیوست کردم رو من حجم رو 1100  حساب میکنم
![IMG_20240315_002806_454](https://github.com/Gozargah/Marzban/assets/136030898/b1a51ccd-bd75-4357-8758-333e3f2a60e1)

2024-03-24 14:41 UTC, realartin commented
> guys, i need this implement it your self or merge this

ما هم همینطور بهش نیاز داریم

2024-07-03 14:06 UTC, closed without merging

2024-07-03 14:07 UTC, SaintShit commented
it's merged to `dev`